version: "3.2"

services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
